### Világrekord mentése

POST http://localhost:8080/api/worldrecords
Content-Type: application/json

{
    "description": "Largest pizza",
    "value": 5.78,
    "unitOfMeasure": "meter",
    "dateOfRecord": "2001-11-11",
    "recorderId": 32
}

### Világrekord mentése - hibakezelés

POST http://localhost:8080/api/worldrecords
Content-Type: application/json

{
  "description": "",
  "value": 5.78,
  "unitOfMeasure": "meter",
  "dateOfRecord": "2001-11-11",
  "recorderId": 32
}

### Rekorder megdönt egy világrekordot (18 pont)

PUT http://localhost:8080/api/worldrecords/12/beatrecords
Content-Type: application/json

{
  "recorderId": 32,
  "value": 6.78
}